# Generated by Django 3.2.5 on 2022-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delayReport', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favStation', models.CharField(max_length=9999)),
                ('favRoute', models.CharField(max_length=9999)),
                ('user_name', models.TextField(db_column='user_id', max_length=30)),
                ('user_pw', models.CharField(max_length=30)),
                ('alarm_time', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(help_text='Schedule ID', primary_key=True, serialize=False)),
                ('contents', models.DateTimeField(help_text='Schedule Datetime')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='MyApp.user')),
            ],
        ),
    ]
