# Generated by Django 3.2.5 on 2022-11-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('content', models.JSONField(default={'end': '', 'start': '', 'waypoint': []})),
            ],
        ),
        migrations.CreateModel(
            name='FavRouteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FavStationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubwayMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='delayReport',
            new_name='totalReport',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alarm_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favRoute',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favStation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pw',
        ),
        migrations.AddField(
            model_name='schedule',
            name='count',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='routeContent',
            field=models.JSONField(default={'end': '', 'start': '', 'waypoint': []}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduleName',
            field=models.CharField(default='My Schedule', help_text='Name of the Schedule', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default='00:00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='week',
            field=models.CharField(choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('son', '일요일')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='홍길동', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SubwayLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNum', models.SmallIntegerField()),
                ('lineId', models.ForeignKey(db_column='subway map', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subway_line_number', to='MyApp.subwaymap')),
            ],
        ),
        migrations.CreateModel(
            name='Staion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(default='', max_length=10)),
                ('stationNum', models.SmallIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timeTable', models.JSONField(default={'arrivalTime': [], 'departureTime': []})),
                ('lineNumber', models.ForeignKey(db_column='linenumber', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_in_line', to='MyApp.subwayline')),
            ],
        ),
        migrations.CreateModel(
            name='FavStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favStationName', models.CharField(default='', max_length=10)),
                ('favstationId', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favStationList', to='MyApp.favstationlist')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='scheduleId',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleList', to='MyApp.schedulelist'),
        ),
    ]
