# Generated by Django 3.2.5 on 2022-11-17 06:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20221114_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(default='', max_length=10)),
                ('stationNum', models.SmallIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timeTable', models.JSONField(default={'arrivalTime': [], 'departureTime': []})),
                ('reported', models.IntegerField(default=0)),
                ('lineNumber', models.ForeignKey(db_column='linenumber', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_in_line', to='MyApp.subwayline')),
            ],
        ),
        migrations.DeleteModel(
            name='FavRouteList',
        ),
        migrations.RemoveField(
            model_name='staion',
            name='lineNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reported',
            new_name='Reported',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='scheduleId',
        ),
        migrations.AddField(
            model_name='favroute',
            name='favRouteId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favstation',
            name='favstationId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduleName',
            field=models.CharField(default='My Schedule', help_text='Name of the Schedule', max_length=30),
        ),
        migrations.DeleteModel(
            name='FavStationList',
        ),
        migrations.DeleteModel(
            name='ScheduleList',
        ),
        migrations.DeleteModel(
            name='Staion',
        ),
    ]
