# Generated by Django 3.2.5 on 2022-11-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20221117_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
