# Generated by Django 3.2.5 on 2022-11-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userKey',
        ),
    ]
