# Generated by Django 3.2.5 on 2022-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_rename_user_id_user_userkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userKey',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
