# Generated by Django 3.2.5 on 2022-11-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_user_userkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userKey',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
