# Generated by Django 3.2.5 on 2022-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20221117_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favroute',
            name='title',
            field=models.CharField(default='My Favorite Route', max_length=30),
        ),
        migrations.AlterField(
            model_name='station',
            name='lineNumber',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='stationNum',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.DeleteModel(
            name='SubwayLine',
        ),
        migrations.DeleteModel(
            name='SubwayMap',
        ),
    ]
