# Generated by Django 3.2.5 on 2022-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20221117_0921'),
    ]

    operations = [
        
    ]
