# Generated by Django 3.2.5 on 2022-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20221117_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AlterField(
            model_name='station',
            name='stationNum',
            field=models.CharField(default='000', max_length=3, primary_key=True, serialize=False),
        ),
    ]
